### ISSUE TITLE
cache won't refresh on index after batch post

### ISSUE THREAD

**Issue by yentsun** [yentsun/price_watch#1]

**Comment by yentsun** [comment]
the familiar error:
```
2015-01-31 05:02:17,215 ERROR [ZODB.Connection][Thread-59] Shouldn't load state for price_watch.models.PriceReport 0x50b9 when the connection is closed
Traceback (most recent call last):
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/ZODB-4.0.1-py2.7.egg/ZODB/Connection.py", line 866, in setstate
    raise ConnectionStateError(msg)
ConnectionStateError: Shouldn't load state for price_watch.models.PriceReport 0x50b9 when the connection is closed
```

**Comment by yentsun** [comment]
```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/yentsun/Projects/price_watch/price_watch/async.py", line 8, in runner
    value = creator()
  File "/home/yentsun/env2/local/lib/python2.7/site-packages/dogpile/cache/region.py", line 1009, in creator
    return fn(*arg, **kw)
  File "/home/yentsun/Projects/price_watch/price_watch/views.py", line 317, in get
    if category.title not in self.CHART_EXCLUDE_LIST:
  File "/home/yentsun/env2/local/lib/python2.7/site-packages/ZODB/Connection.py", line 866, in setstate
    raise ConnectionStateError(msg)
ConnectionStateError: Shouldn't load state for price_watch.models.ProductCategory 0x3f when the connection is closed
```

**Comment by yentsun** [comment]
Seems like https://bitbucket.org/yentsun/price_watch/issue/52, lazy-loading issue

**Comment by yentsun** [comment]
Guess it's time to move to ZEO

**Comment by yentsun** [comment]
After dramatically increasing categories and shops input the issue comes up again:
```
2015-04-03 10:00:34,560 ERROR [ZODB.Connection][Thread-285] Shouldn't load state for price_watch.models.PriceReport 0x55e3 when the connection is closed
Traceback (most recent call last):
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/ZODB-4.0.1-py2.7.egg/ZODB/Connection.py", line 866, in setstate
    raise ConnectionStateError(msg)
ConnectionStateError: Shouldn't load state for price_watch.models.PriceReport 0x55e3 when the connection is closed

```

**Comment by yentsun** [comment]
closed (for now) in https://github.com/yentsun/milk_bot/issues/4

**Comment by yentsun** [comment]
No, reducing payload doesn't solve the problem. It seems that async cache runner connection doesn't have enough resources...
