### ISSUE TITLE
500 @ some reports

### ISSUE THREAD

**Issue by yentsun** [yentsun/price_watch#64]
* http://food-price.net/reports/2f628ce8-51fa-46ea-89b3-4107a6a02daf

**Comment by yentsun** [comment]
Error message:
```
MakoRenderingException: 

Traceback (most recent call last):
  File "/home/yentsun/env2/local/lib/python2.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__
    result = template.render_unicode(**system)
  File "/home/yentsun/env2/local/lib/python2.7/site-packages/mako/template.py", line 452, in render_unicode
    as_unicode=True)
  File "/home/yentsun/env2/local/lib/python2.7/site-packages/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/yentsun/env2/local/lib/python2.7/site-packages/mako/runtime.py", line 835, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/yentsun/env2/local/lib/python2.7/site-packages/mako/runtime.py", line 860, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/yentsun/Projects/price_watch/price_watch/templates/base.mako", line 69, in render_body
    ${next.body()}
  File "/home/yentsun/Projects/price_watch/price_watch/templates/report.mako", line 34, in render_body
    <strong>${req.context.product.get_package_key()}</strong>
  File "/home/yentsun/Projects/price_watch/price_watch/models.py", line 817, in get_package_key
    raise PackageLookupError(self)
PackageLookupError: Package lookup failed for product "\u041a\u0430\u043f\u0443\u0441\u0442\u0430 \u043a\u0440\u0430\u0441\u043d\u043e\u043a\u043e\u0447\u0430\u043d\u043d\u0430\u044f 1,5-3,5\u043a\u0433"
```
