### ISSUE TITLE
500 @ a report view

### ISSUE THREAD

**Issue by yentsun** [yentsun/price_watch#78]
* http://food-price.net/reports/7981b820-4c38-4c8e-ba2b-db22b97139b3
* http://food-price.net/reports/afc1c285-531d-490d-9a32-59b071fedf7f
* http://food-price.net/reports/d368182a-54cf-450f-8d6a-018361b0d286
* ...
19 total

**Comment by yentsun** [comment]
trace:
```
MakoRenderingException: 

Traceback (most recent call last):
  File "/home/yentsun/env2/local/lib/python2.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__
    result = template.render_unicode(**system)
  File "/home/yentsun/env2/local/lib/python2.7/site-packages/mako/template.py", line 452, in render_unicode
    as_unicode=True)
  File "/home/yentsun/env2/local/lib/python2.7/site-packages/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/yentsun/env2/local/lib/python2.7/site-packages/mako/runtime.py", line 835, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/yentsun/env2/local/lib/python2.7/site-packages/mako/runtime.py", line 860, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/yentsun/Projects/price_watch/price_watch/templates/base.mako", line 69, in render_body
    ${next.body()}
  File "/home/yentsun/Projects/price_watch/price_watch/templates/report.mako", line 83, in render_body
    <td>\u0426\u0435\u043d\u0430 \u0437\u0430 ${req.context.product.category.get_data('normal_package')}</td>
AttributeError: 'NoneType' object has no attribute 'get_data'
```

**Comment by yentsun** [comment]
invalid reports removed, continued in #79
