### ISSUE TITLE
TPC in progress

### ISSUE THREAD

**Issue by yentsun** [yentsun/price_watch#80]
2015-11-14 07:29:55,314 CRITI [txn.140115013633792][Dummy-6] A storage error occurred during the second phase of the two-phase commit.  Resources may be in an inconsistent state.
2015-11-14 07:29:55,318 ERROR [txn.140115013633792][Dummy-6] Failed to abort resource manager: <repoze.sendmail.delivery.MailDataManager object at 0x7f6eb0b3d6d0>
Traceback (most recent call last):
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/transaction-1.4.3-py2.7.egg/transaction/_transaction.py", line 453, in abort
    rm.abort(self)
  File "/home/ubuntu/env/lib/python2.7/site-packages/repoze.sendmail-4.2-py2.7.egg/repoze/sendmail/delivery.py", line 119, in abort
    raise ValueError("TPC in progress")
ValueError: TPC in progress
2015-11-14 07:29:55,319 ERROR [waitress][Dummy-6] Exception when serving /reports
Traceback (most recent call last):
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/waitress-0.8.9-py2.7.egg/waitress/channel.py", line 337, in service
    task.service()
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/waitress-0.8.9-py2.7.egg/waitress/task.py", line 173, in service
    self.execute()
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/waitress-0.8.9-py2.7.egg/waitress/task.py", line 392, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 242, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 217, in invoke_subrequest
    response = handle_request(request)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/pyramid_tm-0.9-py2.7.egg/pyramid_tm/__init__.py", line 92, in tm_tween
    manager.abort()
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/transaction-1.4.3-py2.7.egg/transaction/_manager.py", line 116, in abort
    return self.get().abort()
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/transaction-1.4.3-py2.7.egg/transaction/_transaction.py", line 468, in abort
    reraise(t, v, tb)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/transaction-1.4.3-py2.7.egg/transaction/_transaction.py", line 453, in abort
    rm.abort(self)
  File "/home/ubuntu/env/lib/python2.7/site-packages/repoze.sendmail-4.2-py2.7.egg/repoze/sendmail/delivery.py", line 119, in abort
    raise ValueError("TPC in progress")
ValueError: TPC in progress```
```

**Comment by yentsun** [comment]
a known issue with repoze.sendmail https://github.com/repoze/repoze.sendmail/issues/31

**Comment by yentsun** [comment]
`pyramid_mailer` that we use has `repoze.sendmail>=4.1` so, we should implement `repoze.sendmail` directly to pin the version

**Comment by marioidival** [comment]
UP?

**Comment by yentsun** [comment]
@marioidival I guess not

**Comment by marioidival** [comment]
I add repoze.sendmail==4.1 but now appear this error:

A storage error occurred during the second phase of the two-phase commit.  Resources may be in an inconsistent state.
